<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Products</name>
   <tag></tag>
   <elementGuidId>31cf0cec-2512-4a0b-bb5c-ee3c04f4fd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div[2]/details[2]/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Products&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>d675d0b6-287a-4e4f-bf4e-81ff69ceda06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__nav__group__button </value>
      <webElementGuid>69a75e3a-3311-49c9-baad-8d69d5aa55e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>products</value>
      <webElementGuid>b84e0ee4-2f91-4025-bb91-98659e15bfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>gmail: global nav</value>
      <webElementGuid>a7132f35-588c-4c90-8170-4c04c938121b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>in-page interaction</value>
      <webElementGuid>6ee1aa52-6cb1-46f9-96a7-6cbf7cc31abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>event</name>
      <type>Main</type>
      <value>autotrack-data-g</value>
      <webElementGuid>ec82d019-2710-4c9a-b578-a5401a8d897a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fd566c8-5638-46cd-8b5c-5cde80c69924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Products
                </value>
      <webElementGuid>3593f973-3e12-4246-9661-b3ca4fe4b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;header&quot;]/div[@class=&quot;header__desktop-nav header__content&quot;]/div[@class=&quot;header__nav&quot;]/details[@class=&quot;header__nav__group&quot;]/summary[@class=&quot;header__nav__group__button&quot;]</value>
      <webElementGuid>e5e41f6f-847f-4ae2-a2dc-3657e6a0ce8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/details[2]/summary</value>
      <webElementGuid>2c2850b3-32e3-4881-a506-5b4eed580264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::summary[1]</value>
      <webElementGuid>71db6497-dca4-4d37-89fc-99ff4139d212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nonprofits'])[2]/following::summary[1]</value>
      <webElementGuid>8891103d-98d1-4bea-a065-2a45f984385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[3]/preceding::summary[1]</value>
      <webElementGuid>1fe937a0-ec61-4578-95d4-48db30af8e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all apps'])[1]/preceding::summary[1]</value>
      <webElementGuid>a9f2364c-2e1d-4c19-9838-48231216bce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/details[2]/summary</value>
      <webElementGuid>e82e7287-e2a2-4bb7-8a2b-ff7a3436ac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = '
                  Products
                ' or . = '
                  Products
                ')]</value>
      <webElementGuid>5e83f182-99c4-4e3e-890f-d9d09809a630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
