<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Solutions</name>
   <tag></tag>
   <elementGuidId>dbb41a70-f50a-41fc-979b-4c4d753b7ebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>summary.header__nav__group__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div[2]/details/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Solutions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>6edb95f4-7add-4c88-b10d-472c966dd455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__nav__group__button </value>
      <webElementGuid>ad15996f-3dba-461a-a46a-3c91b5af2e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>solutions</value>
      <webElementGuid>945ade70-3d54-4d3c-97c4-733073e4022b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>gmail: global nav</value>
      <webElementGuid>e8af6768-40c0-4707-944d-e4a86a8de558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>in-page interaction</value>
      <webElementGuid>ef3f427e-ce2d-4be8-8645-5544e63de8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>event</name>
      <type>Main</type>
      <value>autotrack-data-g</value>
      <webElementGuid>9a76c1d6-718d-496b-a27c-c012f1f43d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6a4d5d9-355c-49e8-89a3-f7687cd78914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Solutions
                </value>
      <webElementGuid>2503fd32-1a4b-4e63-bbcb-9d9f9c40a805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;header&quot;]/div[@class=&quot;header__desktop-nav header__content&quot;]/div[@class=&quot;header__nav&quot;]/details[@class=&quot;header__nav__group&quot;]/summary[@class=&quot;header__nav__group__button&quot;]</value>
      <webElementGuid>b54c4d55-6b76-46ca-97bb-fd1af67f9a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/details/summary</value>
      <webElementGuid>59d4cf07-2ebc-4ce0-b908-be37c49fb78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[2]/following::summary[1]</value>
      <webElementGuid>8677664a-6bc1-4bbf-bef5-54f200049fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Free Trial'])[1]/following::summary[1]</value>
      <webElementGuid>1b7d798b-bd6e-441f-9872-cb692180ca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[3]/preceding::summary[1]</value>
      <webElementGuid>51a305b3-7fc7-4b9a-b2f0-cf85fdde1047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Business'])[2]/preceding::summary[1]</value>
      <webElementGuid>d3c30f21-ccb2-4702-aa16-7d181f26fc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/details/summary</value>
      <webElementGuid>c3c0dce3-159a-4126-bc4f-f59bfb3b7360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = '
                  Solutions
                ' or . = '
                  Solutions
                ')]</value>
      <webElementGuid>4afb9d6e-f9a8-42e3-9ab5-e1955428b74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
