<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Log In</name>
   <tag></tag>
   <elementGuidId>35b25938-3344-4e95-bd31-3b3d701a8929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>85e49bf2-c5c2-4c59-bf49-4ced0520b6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>98da4292-6633-4bea-a285-8fc6a647c293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;LoginFullPage_loginWrapper__NemNw&quot;]/div[@class=&quot;LoginLayout_container__cHEd5&quot;]/div[@class=&quot;LoginLayout_main__ZMs2+&quot;]/div[@class=&quot;NewLoginPage_container__Y92Wa&quot;]/div[@class=&quot;LoginPanel_login_panel__eQd6J&quot;]/div[@class=&quot;LoginPanel_login_signup__N4spj&quot;]/h2[1]</value>
      <webElementGuid>6b038d01-4043-4204-aeb8-04b2102c4f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder iframe/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>e2653446-3ed5-4945-9f61-8bd4189817f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/h2</value>
      <webElementGuid>6b4ade78-6b4a-491d-9827-ebfc65885afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build and host a website'])[1]/following::h2[1]</value>
      <webElementGuid>8df9c2d0-346a-4205-b134-a95116f9152e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::h2[1]</value>
      <webElementGuid>03b2be0c-135f-4753-956a-1cf18a5135dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>7380e41f-b232-4b0c-b532-e3a23ed0bbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f5562570-70cf-4946-9932-99559321f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>82feb73b-5785-4d4a-8c4e-0ee497794559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
