<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_W3Schools.com</name>
   <tag></tag>
   <elementGuidId>8dfae8ff-2f45-4f0d-adfd-192af2e0a207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='widgetHeaderTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widgetHeaderTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;widget-title&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>83e10493-3cdb-41e7-8508-c98e5774c0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>widget-title</value>
      <webElementGuid>5905be69-5f33-48cd-942a-cf23ee50bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widgetHeaderTitle</value>
      <webElementGuid>4116851c-0894-47a7-93be-78586e40e33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Title-sc-mhgaxb-0 hrFxTj</value>
      <webElementGuid>dcbcc697-7beb-4a1d-ae78-b235d200f06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>W3Schools.com</value>
      <webElementGuid>0ad5c3cc-10ee-409e-b4d0-a12425c03133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widgetHeaderTitle&quot;)</value>
      <webElementGuid>154d993c-2887-487a-8d80-9b17df5a502b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder IF/Page_W3Schools Tryit Editor/iframe_concat(id(, , webWidget, , ))_webWidget</value>
      <webElementGuid>021268f5-07b7-40ce-8ad4-f41e5dcce65a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='widgetHeaderTitle']</value>
      <webElementGuid>fecb2fd9-52d5-4524-ad73-2dd10f237a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Embed']/div/div/div/header/div/h1</value>
      <webElementGuid>6dd25b49-97b7-4397-8de5-a7d7d81f709d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W3Schools.com'])[2]/preceding::h1[1]</value>
      <webElementGuid>3ccc429d-278a-4be0-8af4-f343c0cd92c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/preceding::h1[1]</value>
      <webElementGuid>5d97fc54-ccb6-4de9-b9db-33ffe283faa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='W3Schools.com']/parent::*</value>
      <webElementGuid>4a8f13ed-dbe6-49d4-b8b4-391b808a5182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>34fba048-bedf-4513-95f3-3a2aea07ea84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'widgetHeaderTitle' and (text() = 'W3Schools.com' or . = 'W3Schools.com')]</value>
      <webElementGuid>57b69243-0426-40f6-ba30-7b152a3b9b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
