<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_W3Schools is Powered by W3.CSS_launcher</name>
   <tag></tag>
   <elementGuidId>fbde9867-aef2-4e41-9f9f-4cef267de15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='launcher']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#launcher</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Opens a widget where you can find more information&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bc878003-a334-4c28-a1b3-895b92465396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Opens a widget where you can find more information</value>
      <webElementGuid>718dd521-26ea-48e9-b9a2-e56df693908d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>launcher</value>
      <webElementGuid>1eca5c49-8468-43b1-912d-b988e96cf48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>82dd2038-73fc-48b3-92e3-02de2f4f448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;launcher&quot;)</value>
      <webElementGuid>24209750-2962-4fcf-a06d-bf22fefffd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder IF/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>2f96a632-64f6-4f17-99fb-8ac7b3e33ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='launcher']</value>
      <webElementGuid>181adad3-842e-4d03-a847-549cfa2d4cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>cfdb6fc8-5de4-4901-b788-1b852cee8b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Opens a widget where you can find more information' and @id = 'launcher']</value>
      <webElementGuid>ecbbd2a1-5b3e-4e54-b3cd-4ebda04227b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
