<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Help</name>
   <tag></tag>
   <elementGuidId>330a66a2-64b3-4300-b1ea-3ae1a7c0b3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Embed']/div/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.label-3kk12.Arrange-sizeFit.u-textInheritColor.u-inlineBlock</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;launcher&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3470a94-c587-4f6a-9bff-dcca015b4cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-3kk12 Arrange-sizeFit u-textInheritColor u-inlineBlock </value>
      <webElementGuid>0752bf71-fc34-47aa-98d1-32c03ffae44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>launcher-label</value>
      <webElementGuid>42113f1c-7a4a-4b61-809b-7aebdd1e063f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>13436412-8b46-45ff-b4b8-078081676e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Embed&quot;)/div[1]/div[1]/button[@class=&quot;wrapper-AtBcr u-isActionable u-textLeft u-inlineBlock u-borderNone u-textBold u-textNoWrap Arrange Arrange--middle u-userLauncherColor&quot;]/span[@class=&quot;label-3kk12 Arrange-sizeFit u-textInheritColor u-inlineBlock&quot;]</value>
      <webElementGuid>6a39b53f-49c0-4dd5-b2ae-157b215d56ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder IF/Page_W3Schools Tryit Editor/iframe_W3Schools is Powered by W3.CSS_launcher</value>
      <webElementGuid>90ce8044-1caa-4f11-8384-f911ccad45a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Embed']/div/div/button/span[2]</value>
      <webElementGuid>19452052-6bc6-4765-abe2-8e1da1654fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help']/parent::*</value>
      <webElementGuid>a4e40f8b-e652-48fe-abdf-6c7e1002c4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>6851cf04-41a8-46c4-9295-1bbcb069fc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Help' or . = 'Help')]</value>
      <webElementGuid>d71cef0c-f34d-4702-9cc1-d852d70df337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
