<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>bd6e015a-47e1-48a7-ad02-81c01e7ef6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > svg > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>a315832f-c623-48d8-a7da-14114423f9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z</value>
      <webElementGuid>24a509e4-27b8-44eb-92ec-801d9664fa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;LoginFullPage_loginWrapper__NemNw&quot;]/div[@class=&quot;LoginLayout_container__cHEd5&quot;]/div[@class=&quot;LoginLayout_main__ZMs2+&quot;]/div[@class=&quot;NewLoginPage_container__Y92Wa&quot;]/div[@class=&quot;LoginPanel_login_panel__eQd6J&quot;]/div[@class=&quot;LoginPanel_login_signup__N4spj&quot;]/div[@class=&quot;LoginPanel_form_header_mobile__X0cuF&quot;]/a[2]/svg[1]/path[1]</value>
      <webElementGuid>9d995118-f806-4b6f-bf26-828302b7fd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iFrame/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>490eb8ba-3cb9-4e9d-b5b6-e67cf5431d80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
